
service: CsharpLogin

environment:

provider:
  name: aws
  runtime: dotnetcore3.1
  region: us-east-1
  stackName: CSharpServerless
  timeout: 30
  memorySize: 256


package:
  individually: true

deploymentBucket:
  name: STACKNAME

functions:
  CognitoSignIn:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::CognitoSignIn
    package:
      artifact: bin/release/netcoreapp3.1/cognitoLogin.zip

